name: hng_task3
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  flutter_typeahead: ^4.2.0
  intl: ^0.18.1
  iconify_flutter: ^0.0.5
  pin_code_fields: ^8.0.1
  change_app_package_name: ^1.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Stapel
      fonts:
        - asset: assets/fonts/Stapel-Bold.ttf
        - asset: assets/fonts/Stapel-ExtraBold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
